### ISSUE TITLE
Question about including a segment analytics link in the elle template.

### ISSUE THREAD

**Issue by philpott** [joseariel/elle_tag_manager_template#5]
https://github.com/joseariel/elle_tag_manager_template/blob/70a75095458ebbf94a304514b12f0542bc16ea2f/template.tpl#L71

I'm wondering what is the use for the segment analytics link in the template? It looks like not required for the template to function and would possibly start tracking analytics on the users site.

Thanks
Michael

**Comment by joseariel** [comment]
Michael,

I am including Grigory, who is part of our team and the engineer
responsible for implementing our GTM template for the GTM Gallery.

Let me know if I can assist in any way.


*Joseariel Gomez * | CEO
*m:* (510) 542-3541 <+15105423541>  |  w*:* Elle.shastic.com
<https://elle.shastic.com/>

**Comment by gtereshkoshastic** [comment]
Hello Michael, thank you for the question.

As a part of our solution (https://elle.shastic.com/), we provide our clients with a possibility for tracking users page navigation history and conversions. For this purpose, we use Segment analytics service.
The link is the same for all clients since Segment only aggregates analytics data for all our clients. We store and manage all of the data on the Elle platform.

Hope this explanation helps you.
Let me know if you need further clarifications

**Comment by philpott** [comment]
Thanks for the clarification! 

Since users can look at the code/permissions -- which explicitly call out segment -- could you please include a warning in the tag (description and or in a label on the tag information) that you have a dependency on segment.

Also as this is an official tag implementation from the vendor. Just a quick check to see if you want us to approve the template with it associated to your personal github address or do you want to transfer this to an elle github organization before we approve it?

Thanks
Michael

**Comment by gtereshkoshastic** [comment]
Hello Michal.
Our biggest preference is to get approval for the template and get it published as soon as possible.
We don't need to keep in the GitHub organization right now. But we might want to do this within 12-18 months. Will this be possible? If no, can we get some troubles regarding keeping the template in the non-organization repo?
 
I've updated the description as you aksed. If there are no other obstacles please review and publish it when you have a chance.

Thanks,
Grigory

**Comment by philpott** [comment]
Thats fine, this has cleared the approval process will be publishing it shortly.
